project:
  type: website
  output-dir: docs

website:
  title: "KnowItOwl"
  navbar:
    background: "dark"
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - text: "Chapter1"
        href: chapter1/hello.html
      # - 404.qmd
  # sidebar:
  #   style: "floating"
  #   search: true
  #   contents:
  #     - section: "Basics"
  #       contents:
  #         - index.qmd
  #         - about.qmd
  #     - section: "Layout"
  #       contents:
  #         - index.qmd
  #         - about.qmd
  sidebar: true
    # tools:
    #   - icon: github
    #     href: "https://github.com/teohck"
      # - text: "More"
      #   menu:
      #   - about.qmd
      #   - about.qmd

format:
  html:
    theme:
      dark: [cosmo, theme-dark.scss]
      light: cosmo
    # light: cosmo
    # css: styles.css
    # toc: true



